/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyPapercssStyle {
    }
}
declare global {
    interface HTMLHoneyPapercssStyleElement extends Components.HoneyPapercssStyle, HTMLStencilElement {
    }
    var HTMLHoneyPapercssStyleElement: {
        prototype: HTMLHoneyPapercssStyleElement;
        new (): HTMLHoneyPapercssStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-papercss-style": HTMLHoneyPapercssStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyPapercssStyle {
    }
    interface IntrinsicElements {
        "honey-papercss-style": HoneyPapercssStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-papercss-style": LocalJSX.HoneyPapercssStyle & JSXBase.HTMLAttributes<HTMLHoneyPapercssStyleElement>;
        }
    }
}
