/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyPapercssStyle {
    }
    interface HoneyStyle {
        /**
          * Get the current theme as string in lowercase of tag name.
         */
        "getTheme": () => Promise<string>;
    }
}
declare global {
    interface HTMLHoneyPapercssStyleElement extends Components.HoneyPapercssStyle, HTMLStencilElement {
    }
    var HTMLHoneyPapercssStyleElement: {
        prototype: HTMLHoneyPapercssStyleElement;
        new (): HTMLHoneyPapercssStyleElement;
    };
    interface HTMLHoneyStyleElement extends Components.HoneyStyle, HTMLStencilElement {
    }
    var HTMLHoneyStyleElement: {
        prototype: HTMLHoneyStyleElement;
        new (): HTMLHoneyStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-papercss-style": HTMLHoneyPapercssStyleElement;
        "honey-style": HTMLHoneyStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyPapercssStyle {
    }
    interface HoneyStyle {
    }
    interface IntrinsicElements {
        "honey-papercss-style": HoneyPapercssStyle;
        "honey-style": HoneyStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-papercss-style": LocalJSX.HoneyPapercssStyle & JSXBase.HTMLAttributes<HTMLHoneyPapercssStyleElement>;
            "honey-style": LocalJSX.HoneyStyle & JSXBase.HTMLAttributes<HTMLHoneyStyleElement>;
        }
    }
}
